### ISSUE TITLE
WebSocket

### ISSUE THREAD

**Issue by sm2017** [ptmt/react-native-macos#168]
Is websocket supported? 
If not ,How can I implement it using native code without forking this repository . In other words is it possible to create a plugin for react-native-macos??

**Comment by ptmt** [comment]
Yep, it has full-featured websocket polyfill https://github.com/ptmt/react-native-macos/blob/master/Libraries/WebSocket/WebSocket.js, straight from React Native.

Writing native modules is almost the same process as for iOS, see: https://facebook.github.io/react-native/docs/native-modules-ios.html. If you don't have prior React Native experience, it can be new for you. Ping me on Discord, I can help with specific code.

I'm closing it, since it's more like a question, not an issue. Which I'm hopefully answered.

**Comment by sm2017** [comment]
Thanks can you tell me your discord id??
I need a custom implementation of web socket
