### ISSUE TITLE
Can I use all of node's modules?

### ISSUE THREAD

**Issue by lmatteis** [ptmt/react-native-macos#99]
Can I use all of node's modules with React Native Desktop? Such as `fs`?

**Comment by ptmt** [comment]
Unfortunately, no. At the moment you can do the bridge like Electron does, but it's a certain amount of additional work.

**Comment by matto1990** [comment]
You could take a look at [react-native-fs](https://github.com/johanneslumpe/react-native-fs), however, this will require some changes to make it work with macOS I presume.

**Comment by threepointone** [comment]
Is there some way to run a terminal command? I could get away with starting node in a separate process. Do you suppose there's already a module that could help with this? 

Thanks!

**Comment by ptmt** [comment]
There is no such module, but it's not hard to build, something like `child_process` polyfill, but with worse quality of course. It would be easier to me write initial implementation if you have particular use cases such as node modules you want to use, or even project I can help you with.

**Comment by threepointone** [comment]
I'd be happy to share my usecase! - I'm making [ratpack](https://github.com/threepointone/ratpack), a tool for building and running js. it's basically an electron wrapper around webpack/webpack-dev-server. the problem is, electron makes the app pretty heavy (~65 mb in my case), and it makes autoupdates less pleasant (electron doesn't support delta updates on mac yet). I'd be happy to outsource the 'core' work to a node process, and control/communicate via an RN layer (which I assume will be lighter). There's a lot more to it of course, but this is what I was investigating at the moment.

**Comment by ptmt** [comment]
Great! I'll fork it with proof-of-concept implementation of RN-node module. If it works I can extract it as a stand-alone module. Let's try and see that happens.

**Comment by threepointone** [comment]
Oh! Thank you so much! Please don't go out of your way for this, there's clearly no rush :) Looking forward to it!

**Comment by ptmt** [comment]
I submitted pull request https://github.com/threepointone/ratpack/pull/31 for anyone who interested.
